name: mycar
description: Le couteau Suisse de votre voiture !
version: 1.0.0+1

#homepage: https://cunning.biz
#repository: https://github.com/jachzen/cunning_document_scanner

environment:
  sdk: ">=2.19.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  path_provider: ^2.0.14
  path: ^1.8.3
  sqflite: ^2.3.0
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.1
  provider: ^6.0.5
  flutter_mapbox_navigation: ^0.2.0
  flutter_background_geolocation: ^4.13.4
  background_fetch: ^1.2.1

  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  shared_preferences: ^2.2.0
  location: ^5.0.1
  google_nav_bar: ^5.0.6
  url_launcher: ^6.1.11
  typicons_flutter: ^0.5.0
  dart_date: ^1.2.1
  html: ^0.15.4
  chaleno: ^0.0.6
  flutter_lints: ^2.0.1
  # cunning_document_scanner: ^1.1.2
  io: ^1.0.4
  badges: ^3.1.1
  bloc: ^8.1.1
  cross_file: ^0.3.3+4
  flutter_bloc: ^8.1.2
  flutter_plugin_android_lifecycle: ^2.0.15
  formz: ^0.6.0
  image_picker_android: ^0.8.6+7
  image_picker_ios: ^0.8.7+3
  image_picker_platform_interface: ^2.6.3
  path_provider_android: ^2.0.25
  plugin_platform_interface: ^2.1.4
  sqflite_common: ^2.4.5+1
  synchronized: ^3.1.0
  test_api: 0.6.0
  xdg_directories: ^1.0.0
  equatable: ^2.0.5
  top_snackbar_flutter: ^3.0.0+1
  material_design_icons_flutter: ^6.0.7096
  photo_view: ^0.14.0
  circular_progress_stack: ^0.0.3
  flutter_osm_plugin: ^0.53.2
  percent_indicator: ^4.2.3
  flutter_foreground_task: ^4.2.0
  poly_geofence_service: ^2.0.0
  fl_location: ^2.0.0+1
  flutter_activity_recognition: ^2.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.3.1
  google_fonts: ^4.0.4
  google_mlkit_text_recognition: ^0.10.0
  circular_countdown_timer: ^0.2.3
  numberpicker: ^2.1.2
  http_requests: ^2.6.0
  font_awesome_flutter: ^10.4.0
  webview_flutter: ^4.2.4
  get: ^4.6.5
  share_plus: ^7.0.2
  camera: ^0.10.5+2
  json_serializable: ^6.7.0
  intl: ^0.17.0
  webview_flutter_android: ^3.9.2
  webview_flutter_wkwebview: ^3.7.2
  lints: ^2.1.1
  url_launcher_platform_interface: ^2.1.3
  permission_handler: 10.4.3
  permission_handler_android: 10.3.3
  win32: ^5.0.4
  args: ^2.4.2
  csslib: ^1.0.0
  file: ^6.1.4
  dio: ^5.2.1+1
  geocoding_platform_interface: ^2.0.1
  dart_rss: ^3.0.0
  kdgaugeview: ^1.0.5
  alxgration_speedometer: ^0.0.2
  google_mlkit_commons: ^0.5.0
  flutter_inappwebview: ^6.0.0-beta.24+1
  geolocator: ^10.1.0
  motion_sensors: ^0.1.0
  mvc_pattern: ^1.2.2
  baseflow_plugin_template: ^2.1.2
  xml: ^5.4.1
  web_scraper: ^0.1.4
  http: ^0.13.6
  http_client_helper: ^2.0.4
  flutter_easyloading: ^3.0.5
  animated_loading_indicators: ^1.0.0+2
  buttons_tabbar: ^1.3.7+1
  edge_detection: ^1.1.2
  diacritic: ^0.1.4
  drop_down_list_menu: ^0.0.9
  search_choices: ^2.2.5
  flutter_popup_menu_button: ^0.0.1+5
  elegant_notification: ^1.10.1
  flutter_map: ^4.0.0
  timezone: ^0.8.0
  flutter_tesseract_ocr: ^0.4.24
  open_route_service: ^1.2.2

# connectivity: ^0.4.5+6
#  background_fetch: ^1.1.6

dev_dependencies:
  build_runner: ^2.4.5
#  flutter_test:
#    sdk: flutter

#dependency_overrides:
#  flutter_test:
#    version: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/image1.jpeg
    - assets/images/image2.jpeg
    - assets/images/image3.jpeg
    - assets/images/radar.png
    - assets/images/radar200.png
    - assets/locations.json
