name: mycar
description: Le couteau Suisse de votre voiture !
version: 1.0.0+1

homepage: https://cunning.biz
repository: https://github.com/jachzen/cunning_document_scanner

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  path_provider: ^2.0.14
  path: ^1.8.2
  sqflite: ^2.2.6
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+4
  provider: ^6.0.5


  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  http: ^0.13.6
  shared_preferences: ^2.1.2
  location: ^4.4.0
  google_nav_bar: ^5.0.6
  permission_handler: ^10.3.0
  url_launcher: ^6.1.11
  typicons_flutter: ^0.5.0
  dart_date: ^1.2.1
  html: ^0.15.4
  chaleno: ^0.0.6
  flutter_lints: ^2.0.1
  cunning_document_scanner: ^1.1.2
  io: ^1.0.4
  badges: ^3.1.1
  bloc: ^8.1.1
  cross_file: ^0.3.3+4
  flutter_bloc: ^8.1.2
  flutter_plugin_android_lifecycle: ^2.0.15
  formz: ^0.6.0
  image_picker_android: ^0.8.6+7
  image_picker_ios: ^0.8.7+3
  image_picker_platform_interface: ^2.6.3
  path_provider_android: ^2.0.25
  path_provider_ios: ^2.0.11
  plugin_platform_interface: ^2.1.4
  sqflite_common: ^2.4.5+1
  synchronized: ^3.1.0
  test_api: 0.6.0
  xdg_directories: ^1.0.0
  equatable: ^2.0.5
  top_snackbar_flutter: ^3.0.0+1
  material_design_icons_flutter: ^6.0.7096
  photo_view: ^0.14.0
  circular_progress_stack: ^0.0.3
  flutter_osm_plugin: 0.53.2
  percent_indicator: ^4.2.3
  flutter_foreground_task: ^4.2.0
  activity_recognition_flutter: ^4.2.0
  poly_geofence_service: ^2.0.0
  fl_location: ^2.0.0+1
  flutter_activity_recognition: ^2.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.3.1
  google_fonts: ^4.0.4
  circular_countdown_timer: ^0.2.3
  numberpicker: ^2.1.2
  http_requests: ^2.6.0
  font_awesome_flutter: ^10.4.0
  webview_flutter: ^4.2.2
  get: ^4.6.5
  share_plus: ^7.0.2
  camera: ^0.10.5+2
  google_mlkit_text_recognition: ^0.8.1
  json_serializable: ^6.7.0
  intl: ^0.17.0
  webview_flutter_android: ^3.8.0
  webview_flutter_wkwebview: ^3.5.0
  lints: ^2.1.1
  url_launcher_platform_interface: ^2.1.3
  permission_handler_android: ^10.2.3
  win32: ^5.0.4
  args: ^2.4.2
  csslib: ^1.0.0
  file: ^6.1.4
  dio: ^5.2.1+1
  geocoding_platform_interface: ^2.0.1
  dart_rss: ^3.0.0
  kdgaugeview: ^1.0.5
  alxgration_speedometer: ^0.0.2
  google_mlkit_commons: ^0.4.0
  web_scraper: ^0.1.4
  flutter_inappwebview: ^6.0.0-beta.24+1
  flutter_webview_plugin_ios_android: ^0.3.13+12
  geolocator: ^9.0.2




# connectivity: ^0.4.5+6


#  background_fetch: ^1.1.6



dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/image1.jpeg
    - assets/images/image2.jpeg
    - assets/images/image3.jpeg
    - assets/images/radar.png
    - assets/images/radar200.png
    - assets/locations.json

